// Class: ReadLD
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : LD::LD
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/09       [336393]
Creator        : inutard
Date           : Tue Jan 14 08:55:16 2014
Host           : Linux panlong 3.2.0-37-generic #58-Ubuntu SMP Thu Jan 24 15:28:10 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/inutard/Desktop/tmva-studies/lean_tmva
Training events: 23465
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
# Default:
VerbosityLevel: "Default" [Verbosity level]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 42
(Ht>2500e3)?2500e3:Ht         _Ht_2500e3__2500e3:Ht         (Ht>2500e3)?2500e3:Ht         Ht                            MeV                               'F'    [509029.90625,2500000]
(b_had_pt>700e3)?700e3:b_had_pt _b_had_pt_700e3__700e3:b_had_pt (b_had_pt>700e3)?700e3:b_had_pt Pt(b_had)                       MeV                                 'F'    [25006.7910156,700000]
(b_lep_pt>700e3)?700e3:b_lep_pt _b_lep_pt_700e3__700e3:b_lep_pt (b_lep_pt>700e3)?700e3:b_lep_pt Pt(b_lep)                       MeV                                 'F'    [25007.9375,700000]
lep_pt                        lep_pt                        lep_pt                        lep_pt                        nan                               'F'    [20007.3261719,1097042.25]
lep_eta                       lep_eta                       lep_eta                       lep_eta                       nan                               'F'    [-2.47533321381,2.4819419384]
lep_phi                       lep_phi                       lep_phi                       lep_phi                       nan                               'F'    [-3.14132118225,3.14153909683]
met_et                        met_et                        met_et                        met_et                        nan                               'F'    [988.338867188,1212683.875]
met_phi                       met_phi                       met_phi                       met_phi                       nan                               'F'    [-3.14142751694,3.14110827446]
jet_n                         jet_n                         jet_n                         jet_n                         nan                               'i'    [3,14]
jet_m_max                     jet_m_max                     jet_m_max                     jet_m_max                     nan                               'F'    [60000.265625,179855.5625]
n_btags_70                    n_btags_70                    n_btags_70                    n_btags_70                    nan                               'I'    [0,5]
mwt                           mwt                           mwt                           mwt                           nan                               'F'    [6.92663526535,1539711.625]
Whad_pt                       Whad_pt                       Whad_pt                       Whad_pt                       nan                               'F'    [250003.984375,1428809]
Whad_eta                      Whad_eta                      Whad_eta                      Whad_eta                      nan                               'F'    [-2.33010792732,2.25264978409]
Whad_phi                      Whad_phi                      Whad_phi                      Whad_phi                      nan                               'F'    [-3.14123415947,3.14146661758]
Whad_m                        Whad_m                        Whad_m                        Whad_m                        nan                               'F'    [60000.265625,109937.414062]
Whad_dR                       Whad_dR                       Whad_dR                       Whad_dR                       nan                               'F'    [-1,0.772672593594]
Wlep_pt                       Wlep_pt                       Wlep_pt                       Wlep_pt                       nan                               'F'    [1296.06591797,1374306.875]
Wlep_eta                      Wlep_eta                      Wlep_eta                      Wlep_eta                      nan                               'F'    [-4.75985717773,6.55746221542]
Wlep_phi                      Wlep_phi                      Wlep_phi                      Wlep_phi                      nan                               'F'    [-3.13974118233,3.14140701294]
Wlep_m                        Wlep_m                        Wlep_m                        Wlep_m                        nan                               'F'    [80394.3984375,1539711.625]
b_lep_pt                      b_lep_pt                      b_lep_pt                      b_lep_pt                      nan                               'F'    [25007.9375,1307815.875]
b_had_pt                      b_had_pt                      b_had_pt                      b_had_pt                      nan                               'F'    [25006.7910156,1480084]
tprime_lep_pt                 tprime_lep_pt                 tprime_lep_pt                 tprime_lep_pt                 nan                               'F'    [5714.87841797,1496589.375]
tprime_had_pt                 tprime_had_pt                 tprime_had_pt                 tprime_had_pt                 nan                               'F'    [4196.60595703,1438302.875]
dR_lnu                        dR_lnu                        dR_lnu                        dR_lnu                        nan                               'F'    [0.118681840599,4.50309705734]
dR_lb_lep                     dR_lb_lep                     dR_lb_lep                     dR_lb_lep                     nan                               'F'    [0.400214612484,5.07148122787]
dR_lb_had                     dR_lb_had                     dR_lb_had                     dR_lb_had                     nan                               'F'    [0.401370584965,5.1140370369]
dR_lb1                        dR_lb1                        dR_lb1                        dR_lb1                        nan                               'F'    [0.400214612484,4.93675470352]
dR_lb2                        dR_lb2                        dR_lb2                        dR_lb2                        nan                               'F'    [0.40218693018,5.1140370369]
dR_Wlep_blep                  dR_Wlep_blep                  dR_Wlep_blep                  dR_Wlep_blep                  nan                               'F'    [0.0196545533836,7.90818357468]
dR_Whad_blep                  dR_Whad_blep                  dR_Whad_blep                  dR_Whad_blep                  nan                               'F'    [0.396414637566,5.52754449844]
dR_Whad_bhad                  dR_Whad_bhad                  dR_Whad_bhad                  dR_Whad_bhad                  nan                               'F'    [0.397040575743,4.7444434166]
dR_Whad_b1                    dR_Whad_b1                    dR_Whad_b1                    dR_Whad_b1                    nan                               'F'    [0.396414637566,4.7444434166]
dR_Whad_b2                    dR_Whad_b2                    dR_Whad_b2                    dR_Whad_b2                    nan                               'F'    [0.399091243744,5.52754449844]
mindR_Whad_b                  mindR_Whad_b                  mindR_Whad_b                  mindR_Whad_b                  nan                               'F'    [0.396414637566,4.25239944458]
mindR_lb                      mindR_lb                      mindR_lb                      mindR_lb                      nan                               'F'    [0.400214612484,4.26060628891]
mindR_jj                      mindR_jj                      mindR_jj                      mindR_jj                      nan                               'F'    [0.380293309689,3.63540410995]
mindR_lj                      mindR_lj                      mindR_lj                      mindr_lj                      nan                               'F'    [0.400214612484,3.63768362999]
Mjj_hpt                       Mjj_hpt                       Mjj_hpt                       Mjj_hpt                       nan                               'F'    [63800.75,2115952.5]
Ht                            Ht                            Ht                            Ht                            nan                               'F'    [509029.90625,3296757.25]
m_reco                        m_reco                        m_reco                        m_reco                        nan                               'F'    [75616.296875,1807815.875]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadLD : public IClassifierReader {

 public:

   // constructor
   ReadLD( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadLD" ),
        fNvars( 42 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "(Ht>2500e3)?2500e3:Ht", "(b_had_pt>700e3)?700e3:b_had_pt", "(b_lep_pt>700e3)?700e3:b_lep_pt", "lep_pt", "lep_eta", "lep_phi", "met_et", "met_phi", "jet_n", "jet_m_max", "n_btags_70", "mwt", "Whad_pt", "Whad_eta", "Whad_phi", "Whad_m", "Whad_dR", "Wlep_pt", "Wlep_eta", "Wlep_phi", "Wlep_m", "b_lep_pt", "b_had_pt", "tprime_lep_pt", "tprime_had_pt", "dR_lnu", "dR_lb_lep", "dR_lb_had", "dR_lb1", "dR_lb2", "dR_Wlep_blep", "dR_Whad_blep", "dR_Whad_bhad", "dR_Whad_b1", "dR_Whad_b2", "mindR_Whad_b", "mindR_lb", "mindR_jj", "mindR_lj", "Mjj_hpt", "Ht", "m_reco" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;
      fVmin[13] = -1;
      fVmax[13] = 1;
      fVmin[14] = -1;
      fVmax[14] = 1;
      fVmin[15] = -1;
      fVmax[15] = 1;
      fVmin[16] = -1;
      fVmax[16] = 1;
      fVmin[17] = -1;
      fVmax[17] = 1;
      fVmin[18] = -1;
      fVmax[18] = 1;
      fVmin[19] = -1;
      fVmax[19] = 1;
      fVmin[20] = -1;
      fVmax[20] = 1;
      fVmin[21] = -1;
      fVmax[21] = 1;
      fVmin[22] = -1;
      fVmax[22] = 1;
      fVmin[23] = -1;
      fVmax[23] = 1;
      fVmin[24] = -1;
      fVmax[24] = 1;
      fVmin[25] = -1;
      fVmax[25] = 1;
      fVmin[26] = -1;
      fVmax[26] = 1;
      fVmin[27] = -1;
      fVmax[27] = 1;
      fVmin[28] = -1;
      fVmax[28] = 1;
      fVmin[29] = -1;
      fVmax[29] = 1;
      fVmin[30] = -1;
      fVmax[30] = 1;
      fVmin[31] = -1;
      fVmax[31] = 1;
      fVmin[32] = -1;
      fVmax[32] = 1;
      fVmin[33] = -1;
      fVmax[33] = 1;
      fVmin[34] = -1;
      fVmax[34] = 1;
      fVmin[35] = -1;
      fVmax[35] = 1;
      fVmin[36] = -1;
      fVmax[36] = 1;
      fVmin[37] = -1;
      fVmax[37] = 1;
      fVmin[38] = -1;
      fVmax[38] = 1;
      fVmin[39] = -1;
      fVmax[39] = 1;
      fVmin[40] = -1;
      fVmax[40] = 1;
      fVmin[41] = -1;
      fVmax[41] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'i';
      fType[9] = 'F';
      fType[10] = 'I';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';
      fType[21] = 'F';
      fType[22] = 'F';
      fType[23] = 'F';
      fType[24] = 'F';
      fType[25] = 'F';
      fType[26] = 'F';
      fType[27] = 'F';
      fType[28] = 'F';
      fType[29] = 'F';
      fType[30] = 'F';
      fType[31] = 'F';
      fType[32] = 'F';
      fType[33] = 'F';
      fType[34] = 'F';
      fType[35] = 'F';
      fType[36] = 'F';
      fType[37] = 'F';
      fType[38] = 'F';
      fType[39] = 'F';
      fType[40] = 'F';
      fType[41] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadLD() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][42];
   double fMax_1[3][42];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[42];
   double fVmax[42];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[42];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<double> fLDCoefficients;
};

inline void ReadLD::Initialize() 
{
   fLDCoefficients.push_back( 0.123599212115 );
   fLDCoefficients.push_back( 0.431575872382 );
   fLDCoefficients.push_back( 0.22200761892 );
   fLDCoefficients.push_back( 0.370918120799 );
   fLDCoefficients.push_back( 0.0907952048235 );
   fLDCoefficients.push_back( -0.0279999618705 );
   fLDCoefficients.push_back( -0.013020883252 );
   fLDCoefficients.push_back( 0.0264758523047 );
   fLDCoefficients.push_back( -0.0109867158931 );
   fLDCoefficients.push_back( 0.109065806537 );
   fLDCoefficients.push_back( 0.0435855178911 );
   fLDCoefficients.push_back( 0.17493487548 );
   fLDCoefficients.push_back( 0.115657169759 );
   fLDCoefficients.push_back( -0.019591902433 );
   fLDCoefficients.push_back( 0.00299204086342 );
   fLDCoefficients.push_back( -0.00214346219379 );
   fLDCoefficients.push_back( 0.0382268513572 );
   fLDCoefficients.push_back( -0.0692587644959 );
   fLDCoefficients.push_back( -0.119376967962 );
   fLDCoefficients.push_back( 0.0776397004646 );
   fLDCoefficients.push_back( 0.0265352502934 );
   fLDCoefficients.push_back( 0.346671468074 );
   fLDCoefficients.push_back( -0.530762589176 );
   fLDCoefficients.push_back( -0.304666771191 );
   fLDCoefficients.push_back( 0.0782062688752 );
   fLDCoefficients.push_back( -0.0629282037227 );
   fLDCoefficients.push_back( -0.266601900434 );
   fLDCoefficients.push_back( 2.60297858739 );
   fLDCoefficients.push_back( 2.5832367258 );
   fLDCoefficients.push_back( -2.45873612904 );
   fLDCoefficients.push_back( -2.56508738863 );
   fLDCoefficients.push_back( 0.113470788799 );
   fLDCoefficients.push_back( -1.04910625504 );
   fLDCoefficients.push_back( -0.843422987179 );
   fLDCoefficients.push_back( 0.813475542176 );
   fLDCoefficients.push_back( 0.953956227328 );
   fLDCoefficients.push_back( 0.113342798938 );
   fLDCoefficients.push_back( 0.00982471158227 );
   fLDCoefficients.push_back( -0.000527859060284 );
   fLDCoefficients.push_back( 0.0663682732109 );
   fLDCoefficients.push_back( 0.0738289103654 );
   fLDCoefficients.push_back( -0.449845982528 );
   fLDCoefficients.push_back( 0.0766320143504 );

   // sanity check
   if (fLDCoefficients.size() != fNvars+1) {
      std::cout << "Problem in class \"" << fClassName << "\"::Initialize: mismatch in number of input values"
                << fLDCoefficients.size() << " != " << fNvars+1 << std::endl;
      fStatusIsClean = false;
   }         
}

inline double ReadLD::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double retval = fLDCoefficients[0];
   for (size_t ivar = 1; ivar < fNvars+1; ivar++) {
      retval += fLDCoefficients[ivar]*inputValues[ivar-1];
   }

   return retval;
}

// Clean up
inline void ReadLD::Clear() 
{
   // clear coefficients
   fLDCoefficients.clear(); 
}
   inline double ReadLD::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadLD::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 656194.875;
   fMax_1[0][0] = 2500000;
   fMin_1[1][0] = 509029.90625;
   fMax_1[1][0] = 2500000;
   fMin_1[2][0] = 509029.90625;
   fMax_1[2][0] = 2500000;
   fMin_1[0][1] = 25006.7910156;
   fMax_1[0][1] = 700000;
   fMin_1[1][1] = 25024.984375;
   fMax_1[1][1] = 700000;
   fMin_1[2][1] = 25006.7910156;
   fMax_1[2][1] = 700000;
   fMin_1[0][2] = 25007.9375;
   fMax_1[0][2] = 700000;
   fMin_1[1][2] = 25066.3261719;
   fMax_1[1][2] = 700000;
   fMin_1[2][2] = 25007.9375;
   fMax_1[2][2] = 700000;
   fMin_1[0][3] = 20007.3261719;
   fMax_1[0][3] = 1097042.25;
   fMin_1[1][3] = 20072.9589844;
   fMax_1[1][3] = 906612.9375;
   fMin_1[2][3] = 20007.3261719;
   fMax_1[2][3] = 1097042.25;
   fMin_1[0][4] = -2.47533321381;
   fMax_1[0][4] = 2.4819419384;
   fMin_1[1][4] = -2.4540002346;
   fMax_1[1][4] = 2.398478508;
   fMin_1[2][4] = -2.47533321381;
   fMax_1[2][4] = 2.4819419384;
   fMin_1[0][5] = -3.14097976685;
   fMax_1[0][5] = 3.14153909683;
   fMin_1[1][5] = -3.14132118225;
   fMax_1[1][5] = 3.14025306702;
   fMin_1[2][5] = -3.14132118225;
   fMax_1[2][5] = 3.14153909683;
   fMin_1[0][6] = 988.338867188;
   fMax_1[0][6] = 1212683.875;
   fMin_1[1][6] = 1924.57336426;
   fMax_1[1][6] = 733209.875;
   fMin_1[2][6] = 988.338867188;
   fMax_1[2][6] = 1212683.875;
   fMin_1[0][7] = -3.14142751694;
   fMax_1[0][7] = 3.14110827446;
   fMin_1[1][7] = -3.13981246948;
   fMax_1[1][7] = 3.13971567154;
   fMin_1[2][7] = -3.14142751694;
   fMax_1[2][7] = 3.14110827446;
   fMin_1[0][8] = 3;
   fMax_1[0][8] = 14;
   fMin_1[1][8] = 3;
   fMax_1[1][8] = 12;
   fMin_1[2][8] = 3;
   fMax_1[2][8] = 14;
   fMin_1[0][9] = 60000.265625;
   fMax_1[0][9] = 179855.5625;
   fMin_1[1][9] = 60007.3710938;
   fMax_1[1][9] = 145783.171875;
   fMin_1[2][9] = 60000.265625;
   fMax_1[2][9] = 179855.5625;
   fMin_1[0][10] = 0;
   fMax_1[0][10] = 5;
   fMin_1[1][10] = 0;
   fMax_1[1][10] = 4;
   fMin_1[2][10] = 0;
   fMax_1[2][10] = 5;
   fMin_1[0][11] = 6.92663526535;
   fMax_1[0][11] = 1539711.625;
   fMin_1[1][11] = 14.7136697769;
   fMax_1[1][11] = 897116.8125;
   fMin_1[2][11] = 6.92663526535;
   fMax_1[2][11] = 1539711.625;
   fMin_1[0][12] = 250024.578125;
   fMax_1[0][12] = 1428809;
   fMin_1[1][12] = 250003.984375;
   fMax_1[1][12] = 1104952.125;
   fMin_1[2][12] = 250003.984375;
   fMax_1[2][12] = 1428809;
   fMin_1[0][13] = -2.19293570518;
   fMax_1[0][13] = 2.14992332458;
   fMin_1[1][13] = -2.33010792732;
   fMax_1[1][13] = 2.25264978409;
   fMin_1[2][13] = -2.33010792732;
   fMax_1[2][13] = 2.25264978409;
   fMin_1[0][14] = -3.14123415947;
   fMax_1[0][14] = 3.14133787155;
   fMin_1[1][14] = -3.14103412628;
   fMax_1[1][14] = 3.14146661758;
   fMin_1[2][14] = -3.14123415947;
   fMax_1[2][14] = 3.14146661758;
   fMin_1[0][15] = 60000.265625;
   fMax_1[0][15] = 109937.414062;
   fMin_1[1][15] = 60007.3710938;
   fMax_1[1][15] = 109307.53125;
   fMin_1[2][15] = 60000.265625;
   fMax_1[2][15] = 109937.414062;
   fMin_1[0][16] = -1;
   fMax_1[0][16] = 0.772672593594;
   fMin_1[1][16] = -1;
   fMax_1[1][16] = 0.75494235754;
   fMin_1[2][16] = -1;
   fMax_1[2][16] = 0.772672593594;
   fMin_1[0][17] = 1296.06591797;
   fMax_1[0][17] = 1374306.875;
   fMin_1[1][17] = 5387.9765625;
   fMax_1[1][17] = 878536.375;
   fMin_1[2][17] = 1296.06591797;
   fMax_1[2][17] = 1374306.875;
   fMin_1[0][18] = -4.75985717773;
   fMax_1[0][18] = 6.55746221542;
   fMin_1[1][18] = -4.1175570488;
   fMax_1[1][18] = 4.16320085526;
   fMin_1[2][18] = -4.75985717773;
   fMax_1[2][18] = 6.55746221542;
   fMin_1[0][19] = -3.13974118233;
   fMax_1[0][19] = 3.14140701294;
   fMin_1[1][19] = -3.13956427574;
   fMax_1[1][19] = 3.13840198517;
   fMin_1[2][19] = -3.13974118233;
   fMax_1[2][19] = 3.14140701294;
   fMin_1[0][20] = 80394.3984375;
   fMax_1[0][20] = 1539711.625;
   fMin_1[1][20] = 80395.4921875;
   fMax_1[1][20] = 897116.8125;
   fMin_1[2][20] = 80394.3984375;
   fMax_1[2][20] = 1539711.625;
   fMin_1[0][21] = 25007.9375;
   fMax_1[0][21] = 1169934.875;
   fMin_1[1][21] = 25066.3261719;
   fMax_1[1][21] = 1307815.875;
   fMin_1[2][21] = 25007.9375;
   fMax_1[2][21] = 1307815.875;
   fMin_1[0][22] = 25006.7910156;
   fMax_1[0][22] = 1480084;
   fMin_1[1][22] = 25024.984375;
   fMax_1[1][22] = 1120832.25;
   fMin_1[2][22] = 25006.7910156;
   fMax_1[2][22] = 1480084;
   fMin_1[0][23] = 5714.87841797;
   fMax_1[0][23] = 1496589.375;
   fMin_1[1][23] = 15620.9775391;
   fMax_1[1][23] = 1105221.125;
   fMin_1[2][23] = 5714.87841797;
   fMax_1[2][23] = 1496589.375;
   fMin_1[0][24] = 4196.60595703;
   fMax_1[0][24] = 1438302.875;
   fMin_1[1][24] = 32876.2382812;
   fMax_1[1][24] = 1173914.875;
   fMin_1[2][24] = 4196.60595703;
   fMax_1[2][24] = 1438302.875;
   fMin_1[0][25] = 0.118681840599;
   fMax_1[0][25] = 4.50309705734;
   fMin_1[1][25] = 0.212075054646;
   fMax_1[1][25] = 4.34393835068;
   fMin_1[2][25] = 0.118681840599;
   fMax_1[2][25] = 4.50309705734;
   fMin_1[0][26] = 0.400706261396;
   fMax_1[0][26] = 5.07148122787;
   fMin_1[1][26] = 0.400214612484;
   fMax_1[1][26] = 4.46510267258;
   fMin_1[2][26] = 0.400214612484;
   fMax_1[2][26] = 5.07148122787;
   fMin_1[0][27] = 0.401370584965;
   fMax_1[0][27] = 5.1140370369;
   fMin_1[1][27] = 0.403047084808;
   fMax_1[1][27] = 4.92583847046;
   fMin_1[2][27] = 0.401370584965;
   fMax_1[2][27] = 5.1140370369;
   fMin_1[0][28] = 0.400706261396;
   fMax_1[0][28] = 4.93675470352;
   fMin_1[1][28] = 0.400214612484;
   fMax_1[1][28] = 4.92583847046;
   fMin_1[2][28] = 0.400214612484;
   fMax_1[2][28] = 4.93675470352;
   fMin_1[0][29] = 0.40218693018;
   fMax_1[0][29] = 5.1140370369;
   fMin_1[1][29] = 0.403249502182;
   fMax_1[1][29] = 4.46510267258;
   fMin_1[2][29] = 0.40218693018;
   fMax_1[2][29] = 5.1140370369;
   fMin_1[0][30] = 0.0196545533836;
   fMax_1[0][30] = 7.90818357468;
   fMin_1[1][30] = 0.0351399816573;
   fMax_1[1][30] = 5.8540520668;
   fMin_1[2][30] = 0.0196545533836;
   fMax_1[2][30] = 7.90818357468;
   fMin_1[0][31] = 0.397312879562;
   fMax_1[0][31] = 4.74415063858;
   fMin_1[1][31] = 0.396414637566;
   fMax_1[1][31] = 5.52754449844;
   fMin_1[2][31] = 0.396414637566;
   fMax_1[2][31] = 5.52754449844;
   fMin_1[0][32] = 0.397040575743;
   fMax_1[0][32] = 4.7444434166;
   fMin_1[1][32] = 0.4077924788;
   fMax_1[1][32] = 4.42310571671;
   fMin_1[2][32] = 0.397040575743;
   fMax_1[2][32] = 4.7444434166;
   fMin_1[0][33] = 0.397040575743;
   fMax_1[0][33] = 4.7444434166;
   fMin_1[1][33] = 0.396414637566;
   fMax_1[1][33] = 4.56018877029;
   fMin_1[2][33] = 0.396414637566;
   fMax_1[2][33] = 4.7444434166;
   fMin_1[0][34] = 0.403430253267;
   fMax_1[0][34] = 4.74415063858;
   fMin_1[1][34] = 0.399091243744;
   fMax_1[1][34] = 5.52754449844;
   fMin_1[2][34] = 0.399091243744;
   fMax_1[2][34] = 5.52754449844;
   fMin_1[0][35] = 0.397040575743;
   fMax_1[0][35] = 4.04857540131;
   fMin_1[1][35] = 0.396414637566;
   fMax_1[1][35] = 4.25239944458;
   fMin_1[2][35] = 0.396414637566;
   fMax_1[2][35] = 4.25239944458;
   fMin_1[0][36] = 0.400706261396;
   fMax_1[0][36] = 3.91956186295;
   fMin_1[1][36] = 0.400214612484;
   fMax_1[1][36] = 4.26060628891;
   fMin_1[2][36] = 0.400214612484;
   fMax_1[2][36] = 4.26060628891;
   fMin_1[0][37] = 0.380293309689;
   fMax_1[0][37] = 3.63540410995;
   fMin_1[1][37] = 0.394029647112;
   fMax_1[1][37] = 3.12130403519;
   fMin_1[2][37] = 0.380293309689;
   fMax_1[2][37] = 3.63540410995;
   fMin_1[0][38] = 0.400706261396;
   fMax_1[0][38] = 3.63768362999;
   fMin_1[1][38] = 0.400214612484;
   fMax_1[1][38] = 3.14345645905;
   fMin_1[2][38] = 0.400214612484;
   fMax_1[2][38] = 3.63768362999;
   fMin_1[0][39] = 63800.75;
   fMax_1[0][39] = 2115952.5;
   fMin_1[1][39] = 77291.421875;
   fMax_1[1][39] = 2079320;
   fMin_1[2][39] = 63800.75;
   fMax_1[2][39] = 2115952.5;
   fMin_1[0][40] = 656194.875;
   fMax_1[0][40] = 3296757.25;
   fMin_1[1][40] = 509029.90625;
   fMax_1[1][40] = 2813130;
   fMin_1[2][40] = 509029.90625;
   fMax_1[2][40] = 3296757.25;
   fMin_1[0][41] = 78595.5078125;
   fMax_1[0][41] = 1807815.875;
   fMin_1[1][41] = 75616.296875;
   fMax_1[1][41] = 1656369.875;
   fMin_1[2][41] = 75616.296875;
   fMax_1[2][41] = 1807815.875;
}

//_______________________________________________________________________
inline void ReadLD::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 42;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesGet.push_back( 11);
   indicesGet.push_back( 12);
   indicesGet.push_back( 13);
   indicesGet.push_back( 14);
   indicesGet.push_back( 15);
   indicesGet.push_back( 16);
   indicesGet.push_back( 17);
   indicesGet.push_back( 18);
   indicesGet.push_back( 19);
   indicesGet.push_back( 20);
   indicesGet.push_back( 21);
   indicesGet.push_back( 22);
   indicesGet.push_back( 23);
   indicesGet.push_back( 24);
   indicesGet.push_back( 25);
   indicesGet.push_back( 26);
   indicesGet.push_back( 27);
   indicesGet.push_back( 28);
   indicesGet.push_back( 29);
   indicesGet.push_back( 30);
   indicesGet.push_back( 31);
   indicesGet.push_back( 32);
   indicesGet.push_back( 33);
   indicesGet.push_back( 34);
   indicesGet.push_back( 35);
   indicesGet.push_back( 36);
   indicesGet.push_back( 37);
   indicesGet.push_back( 38);
   indicesGet.push_back( 39);
   indicesGet.push_back( 40);
   indicesGet.push_back( 41);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);
   indicesPut.push_back( 11);
   indicesPut.push_back( 12);
   indicesPut.push_back( 13);
   indicesPut.push_back( 14);
   indicesPut.push_back( 15);
   indicesPut.push_back( 16);
   indicesPut.push_back( 17);
   indicesPut.push_back( 18);
   indicesPut.push_back( 19);
   indicesPut.push_back( 20);
   indicesPut.push_back( 21);
   indicesPut.push_back( 22);
   indicesPut.push_back( 23);
   indicesPut.push_back( 24);
   indicesPut.push_back( 25);
   indicesPut.push_back( 26);
   indicesPut.push_back( 27);
   indicesPut.push_back( 28);
   indicesPut.push_back( 29);
   indicesPut.push_back( 30);
   indicesPut.push_back( 31);
   indicesPut.push_back( 32);
   indicesPut.push_back( 33);
   indicesPut.push_back( 34);
   indicesPut.push_back( 35);
   indicesPut.push_back( 36);
   indicesPut.push_back( 37);
   indicesPut.push_back( 38);
   indicesPut.push_back( 39);
   indicesPut.push_back( 40);
   indicesPut.push_back( 41);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<42;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadLD::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadLD::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
