// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/09       [336393]
Creator        : inutard
Date           : Mon Jan 13 22:06:04 2014
Host           : Linux panlong 3.2.0-37-generic #58-Ubuntu SMP Thu Jan 24 15:28:10 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/inutard/Desktop/tmva-studies/lean_tmva
Training events: 23465
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 7
n_btags_70                    n_btags_70                    n_btags_70                    n_btags_70                    nan                               'I'    [0,5]
Whad_eta                      Whad_eta                      Whad_eta                      Whad_eta                      nan                               'F'    [-2.33010792732,2.25264978409]
Wlep_phi                      Wlep_phi                      Wlep_phi                      Wlep_phi                      nan                               'F'    [-3.13974118233,3.14140701294]
tprime_had_pt                 tprime_had_pt                 tprime_had_pt                 tprime_had_pt                 nan                               'F'    [4196.60595703,1438302.875]
dR_lb_had                     dR_lb_had                     dR_lb_had                     dR_lb_had                     nan                               'F'    [0.401370584965,5.1140370369]
dR_lb1                        dR_lb1                        dR_lb1                        dR_lb1                        nan                               'F'    [0.400214612484,4.93675470352]
Mjj_hpt                       Mjj_hpt                       Mjj_hpt                       Mjj_hpt                       nan                               'F'    [63800.75,2115952.5]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 7 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "n_btags_70", "Whad_eta", "Wlep_phi", "tprime_had_pt", "dR_lb_had", "dR_lb1", "Mjj_hpt" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;

      // initialize input variable types
      fType[0] = 'I';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][7];
   double fMax_1[3][7];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[7];
   double fVmax[7];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[7];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[13][8];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][13];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 8; fWeights[0] = new double[8]; 
   fLayerSize[1] = 13; fWeights[1] = new double[13]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.157602281582008;
   fWeightMatrix0to1[1][0] = 1.8328562755581;
   fWeightMatrix0to1[2][0] = 0.0629224993702896;
   fWeightMatrix0to1[3][0] = 0.263840235000834;
   fWeightMatrix0to1[4][0] = -2.53773565046007;
   fWeightMatrix0to1[5][0] = -1.86675420902855;
   fWeightMatrix0to1[6][0] = -0.17395812972902;
   fWeightMatrix0to1[7][0] = -0.0345936186417543;
   fWeightMatrix0to1[8][0] = -0.881614638873365;
   fWeightMatrix0to1[9][0] = -0.216271771592495;
   fWeightMatrix0to1[10][0] = -0.157390889019827;
   fWeightMatrix0to1[11][0] = -0.306248693506602;
   fWeightMatrix0to1[0][1] = -0.0367383293964406;
   fWeightMatrix0to1[1][1] = -0.306731216796381;
   fWeightMatrix0to1[2][1] = 0.0169850738530316;
   fWeightMatrix0to1[3][1] = -0.0944243205798988;
   fWeightMatrix0to1[4][1] = -0.792980124928155;
   fWeightMatrix0to1[5][1] = 0.819007282408985;
   fWeightMatrix0to1[6][1] = 0.339940636903177;
   fWeightMatrix0to1[7][1] = 1.38103214361861;
   fWeightMatrix0to1[8][1] = 0.0597274228825281;
   fWeightMatrix0to1[9][1] = -0.360727680320317;
   fWeightMatrix0to1[10][1] = -0.127987623830294;
   fWeightMatrix0to1[11][1] = 0.330934719401265;
   fWeightMatrix0to1[0][2] = 0.00961649585512609;
   fWeightMatrix0to1[1][2] = -0.0339988586080612;
   fWeightMatrix0to1[2][2] = 0.0288728166374874;
   fWeightMatrix0to1[3][2] = 0.0524935402949173;
   fWeightMatrix0to1[4][2] = 0.0540666754931778;
   fWeightMatrix0to1[5][2] = -0.120258564139143;
   fWeightMatrix0to1[6][2] = -0.0688287913352727;
   fWeightMatrix0to1[7][2] = -0.0803147508907627;
   fWeightMatrix0to1[8][2] = -0.135117102269809;
   fWeightMatrix0to1[9][2] = 0.0634273441165457;
   fWeightMatrix0to1[10][2] = 0.0962682188067805;
   fWeightMatrix0to1[11][2] = 0.0311712656993235;
   fWeightMatrix0to1[0][3] = -0.790011389228223;
   fWeightMatrix0to1[1][3] = 1.29507346694319;
   fWeightMatrix0to1[2][3] = -0.33387585186776;
   fWeightMatrix0to1[3][3] = 0.134284178864241;
   fWeightMatrix0to1[4][3] = 0.804448525962337;
   fWeightMatrix0to1[5][3] = -0.59196822805164;
   fWeightMatrix0to1[6][3] = 0.389578344124462;
   fWeightMatrix0to1[7][3] = 0.109108370371359;
   fWeightMatrix0to1[8][3] = -0.349327400836527;
   fWeightMatrix0to1[9][3] = -0.634347148808286;
   fWeightMatrix0to1[10][3] = 0.94690139403829;
   fWeightMatrix0to1[11][3] = 0.528680544490627;
   fWeightMatrix0to1[0][4] = 0.347592277340759;
   fWeightMatrix0to1[1][4] = 0.983068694647862;
   fWeightMatrix0to1[2][4] = 0.407625040937931;
   fWeightMatrix0to1[3][4] = 0.296773751336819;
   fWeightMatrix0to1[4][4] = -0.286126567910825;
   fWeightMatrix0to1[5][4] = 0.473465964473103;
   fWeightMatrix0to1[6][4] = -0.262722753046178;
   fWeightMatrix0to1[7][4] = -0.170757124870184;
   fWeightMatrix0to1[8][4] = 0.0459443513127001;
   fWeightMatrix0to1[9][4] = -0.0373358550081869;
   fWeightMatrix0to1[10][4] = 0.262339989275521;
   fWeightMatrix0to1[11][4] = 0.651137822074331;
   fWeightMatrix0to1[0][5] = -0.422376911934149;
   fWeightMatrix0to1[1][5] = 0.178507025973137;
   fWeightMatrix0to1[2][5] = -0.20294228600536;
   fWeightMatrix0to1[3][5] = -0.0372473286090504;
   fWeightMatrix0to1[4][5] = 1.49966582677694;
   fWeightMatrix0to1[5][5] = -2.15909422702521;
   fWeightMatrix0to1[6][5] = 0.578535069743137;
   fWeightMatrix0to1[7][5] = 0.542569200778174;
   fWeightMatrix0to1[8][5] = 0.0314620768073818;
   fWeightMatrix0to1[9][5] = -0.171469083352572;
   fWeightMatrix0to1[10][5] = -0.228953498738136;
   fWeightMatrix0to1[11][5] = -0.372853688631272;
   fWeightMatrix0to1[0][6] = 0.17560371030477;
   fWeightMatrix0to1[1][6] = 1.36571139094961;
   fWeightMatrix0to1[2][6] = 0.90356523588893;
   fWeightMatrix0to1[3][6] = -0.652787762310644;
   fWeightMatrix0to1[4][6] = -2.30838353017778;
   fWeightMatrix0to1[5][6] = -1.9554479430525;
   fWeightMatrix0to1[6][6] = 0.583401860565432;
   fWeightMatrix0to1[7][6] = 0.190152017995223;
   fWeightMatrix0to1[8][6] = 1.49214299424377;
   fWeightMatrix0to1[9][6] = -0.141780954969246;
   fWeightMatrix0to1[10][6] = -0.0777996298671211;
   fWeightMatrix0to1[11][6] = 0.184556934874681;
   fWeightMatrix0to1[0][7] = -0.252132213154553;
   fWeightMatrix0to1[1][7] = -1.31266785832351;
   fWeightMatrix0to1[2][7] = 0.763225564267688;
   fWeightMatrix0to1[3][7] = 0.0209788657627799;
   fWeightMatrix0to1[4][7] = -4.91488085252143;
   fWeightMatrix0to1[5][7] = -4.94492117425518;
   fWeightMatrix0to1[6][7] = 0.339606727575655;
   fWeightMatrix0to1[7][7] = 1.36204196506833;
   fWeightMatrix0to1[8][7] = 0.936338570246605;
   fWeightMatrix0to1[9][7] = -0.685594371663015;
   fWeightMatrix0to1[10][7] = -0.118548314053256;
   fWeightMatrix0to1[11][7] = 0.430151477997799;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.116796245168663;
   fWeightMatrix1to2[0][1] = 0.116136211445586;
   fWeightMatrix1to2[0][2] = 0.0827930464593158;
   fWeightMatrix1to2[0][3] = 0.214799402957006;
   fWeightMatrix1to2[0][4] = -0.647309439896021;
   fWeightMatrix1to2[0][5] = -0.44716731095808;
   fWeightMatrix1to2[0][6] = -0.276729392191095;
   fWeightMatrix1to2[0][7] = 0.409306856383861;
   fWeightMatrix1to2[0][8] = 0.273320395712844;
   fWeightMatrix1to2[0][9] = 0.0203002275455619;
   fWeightMatrix1to2[0][10] = 0.240456500847018;
   fWeightMatrix1to2[0][11] = -0.254627959933339;
   fWeightMatrix1to2[0][12] = -0.381932736324222;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0;
   fMax_1[0][0] = 5;
   fMin_1[1][0] = 0;
   fMax_1[1][0] = 4;
   fMin_1[2][0] = 0;
   fMax_1[2][0] = 5;
   fMin_1[0][1] = -2.19293570518;
   fMax_1[0][1] = 2.14992332458;
   fMin_1[1][1] = -2.33010792732;
   fMax_1[1][1] = 2.25264978409;
   fMin_1[2][1] = -2.33010792732;
   fMax_1[2][1] = 2.25264978409;
   fMin_1[0][2] = -3.13974118233;
   fMax_1[0][2] = 3.14140701294;
   fMin_1[1][2] = -3.13956427574;
   fMax_1[1][2] = 3.13840198517;
   fMin_1[2][2] = -3.13974118233;
   fMax_1[2][2] = 3.14140701294;
   fMin_1[0][3] = 4196.60595703;
   fMax_1[0][3] = 1438302.875;
   fMin_1[1][3] = 32876.2382812;
   fMax_1[1][3] = 1173914.875;
   fMin_1[2][3] = 4196.60595703;
   fMax_1[2][3] = 1438302.875;
   fMin_1[0][4] = 0.401370584965;
   fMax_1[0][4] = 5.1140370369;
   fMin_1[1][4] = 0.403047084808;
   fMax_1[1][4] = 4.92583847046;
   fMin_1[2][4] = 0.401370584965;
   fMax_1[2][4] = 5.1140370369;
   fMin_1[0][5] = 0.400706261396;
   fMax_1[0][5] = 4.93675470352;
   fMin_1[1][5] = 0.400214612484;
   fMax_1[1][5] = 4.92583847046;
   fMin_1[2][5] = 0.400214612484;
   fMax_1[2][5] = 4.93675470352;
   fMin_1[0][6] = 63800.75;
   fMax_1[0][6] = 2115952.5;
   fMin_1[1][6] = 77291.421875;
   fMax_1[1][6] = 2079320;
   fMin_1[2][6] = 63800.75;
   fMax_1[2][6] = 2115952.5;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 7;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<7;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
