// Class: ReadRuleFit
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : RuleFit::RuleFit
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/01       [335873]
Creator        : inutard
Date           : Thu Sep 19 23:57:08 2013
Host           : Linux lxbuild148.cern.ch 2.6.18-238.5.1.el5 #1 SMP Wed Mar 2 15:08:52 CET 2011 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/inutard/thesis
Training events: 6000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "True" [Print method-specific help message]
GDTau: "-1.000000e+00" [Gradient-directed (GD) path: default fit cut-off]
GDTauPrec: "1.000000e-02" [GD path: precision of tau]
GDStep: "1.000000e-02" [GD path: step size]
GDNSteps: "10000" [GD path: number of steps]
GDErrScale: "1.020000e+00" [Stop scan when error > scale*errmin]
fEventsMin: "1.000000e-02" [Minimum fraction of events in a splittable node]
fEventsMax: "5.000000e-01" [Maximum fraction of events in a splittable node]
nTrees: "20" [Number of trees in forest.]
RuleMinDist: "1.000000e-03" [Minimum distance between rules]
MinImp: "1.000000e-03" [Minimum rule importance accepted]
Model: "modrulelinear" [Model to be used]
RuleFitModule: "rftmva" [Which RuleFit module to use]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LinQuantile: "2.500000e-02" [Quantile of linear terms (removes outliers)]
GDPathEveFrac: "5.000000e-01" [Fraction of events used for the path search]
GDValidEveFrac: "5.000000e-01" [Fraction of events used for the validation]
ForestType: "adaboost" [Method to use for forest generation (AdaBoost or RandomForest)]
RFWorkDir: "./rulefit" [Friedman's RuleFit module (RFF): working dir]
RFNrules: "2000" [RFF: Mximum number of rules]
RFNendnodes: "4" [RFF: Average number of end nodes]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
var1+var2                     myvar1                        myvar1                        myvar1                                                          'F'    [-8.96602058411,7.69307804108]
var1-var2                     myvar2                        myvar2                        Expression 2                                                    'F'    [-4.08540010452,4.0258936882]
var3                          var3                          var3                          Variable 3                    units                             'F'    [-5.05078554153,4.35967063904]
var4                          var4                          var4                          Variable 4                    units                             'F'    [-5.95050764084,4.92254400253]
NSpec 2
var1*2                        spec1                         spec1                         Spectator 1                   units                             'F'    [-9.91655540466,9.52782058716]
var1*3                        spec2                         spec2                         Spectator 2                   units                             'F'    [-14.874833107,14.2917308807]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadRuleFit : public IClassifierReader {

 public:

   // constructor
   ReadRuleFit( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadRuleFit" ),
        fNvars( 4 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "var1+var2", "var1-var2", "var3", "var4" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -8.96602058410645;
      fVmax[0] = 7.69307804107666;
      fVmin[1] = -4.08540010452271;
      fVmax[1] = 4.0258936882019;
      fVmin[2] = -5.05078554153442;
      fVmax[2] = 4.35967063903809;
      fVmin[3] = -5.95050764083862;
      fVmax[3] = 4.92254400253296;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadRuleFit() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   // not implemented for class: "ReadRuleFit"
};
void   ReadRuleFit::Initialize(){}
void   ReadRuleFit::Clear(){}
double ReadRuleFit::GetMvaValue__( const std::vector<double>& inputValues ) const {
   double rval=12.43984192;
   //
   // here follows all rules ordered in importance (most important first)
   // at the end of each line, the relative importance of the rule is given
   //
   if ((inputValues[3]<0.2626647353)) rval+=-0.7515919015;   // importance = 0.338
   if ((-0.2550996244<inputValues[3])) rval+=-0.6770763777;   // importance = 0.295
   if ((1.346754789<inputValues[0])) rval+=-0.7653870722;   // importance = 0.288
   if ((0.326617986<inputValues[2])) rval+=-0.6544731651;   // importance = 0.287
   if ((inputValues[0]<-0.6504082084)&&(inputValues[3]<-0.008489469998)) rval+=-0.6468054119;   // importance = 0.274
   if ((inputValues[3]<-0.7728639841)) rval+=-0.6775355134;   // importance = 0.264
   if ((inputValues[0]<-0.1289403141)&&(inputValues[3]<-0.7728639841)) rval+=-0.6776701173;   // importance = 0.263
   if ((-1.174188495<inputValues[2])&&(-0.2550996244<inputValues[3])) rval+=-0.5806456366;   // importance = 0.254
   if ((inputValues[1]<-0.2228792459)) rval+=-0.5628858047;   // importance = 0.252
   if ((inputValues[3]<0.7804290652)) rval+=-0.5926319821;   // importance = 0.248
   if ((inputValues[1]<-0.6091313362)) rval+=-0.5900669647;   // importance = 0.244
   if ((-1.826406837<inputValues[0])&&(0.6982845068<inputValues[3])) rval+=-0.5690013061;   // importance = 0.242
   if ((inputValues[3]<1.150868058)) rval+=-0.5978805856;   // importance = 0.223
   if ((-0.2228792459<inputValues[1])) rval+=-0.4927926545;   // importance = 0.220
   if ((inputValues[0]<1.845093489)&&(inputValues[3]<0.6450840235)) rval+=-0.5014767625;   // importance = 0.215
   if ((inputValues[0]<2.179115534)&&(inputValues[3]<1.150868058)) rval+=-0.5461944861;   // importance = 0.206
   if ((0.7804290652<inputValues[3])) rval+=-0.4628658869;   // importance = 0.194
   if ((-0.6091313362<inputValues[1])) rval+=-0.4654458287;   // importance = 0.192
   if ((-1.826406837<inputValues[0])) rval+=-0.5919029944;   // importance = 0.190
   if ((inputValues[3]<1.815957785)) rval+=-0.7177090894;   // importance = 0.188
   if ((-1.017732859<inputValues[2])) rval+=-0.5311371021;   // importance = 0.180
   if ((inputValues[0]<4.031854153)&&(inputValues[3]<1.815957785)) rval+=-0.6869704984;   // importance = 0.180
   if ((inputValues[2]<-1.017732859)) rval+=-0.5263977261;   // importance = 0.178
   if ((-1.290628314<inputValues[3])) rval+=-0.5717026048;   // importance = 0.177
   if ((inputValues[2]<0.326617986)) rval+=-0.4013776977;   // importance = 0.176
   if ((inputValues[0]<2.933335543)&&(inputValues[3]<0.6765475869)) rval+=-0.4077658567;   // importance = 0.174
   if ((-2.20457983<inputValues[0])&&(-0.7728639841<inputValues[3])) rval+=-0.4224741744;   // importance = 0.166
   if ((inputValues[0]<1.357761383)&&(inputValues[3]<-0.2550996244)) rval+=-0.3787863004;   // importance = 0.165
   if ((inputValues[0]<1.845093489)&&(inputValues[3]<-0.2550996244)) rval+=-0.3787863004;   // importance = 0.165
   if ((inputValues[3]<-0.2550996244)) rval+=-0.3787863004;   // importance = 0.165
   if ((inputValues[2]<-0.4694648087)&&(inputValues[3]<-1.290628314)) rval+=-0.5093861144;   // importance = 0.153
   if ((inputValues[2]<0.4963622689)&&(inputValues[3]<-1.290628314)) rval+=-0.4843580058;   // importance = 0.150
   if ((inputValues[3]<-1.290628314)) rval+=-0.4843580058;   // importance = 0.150
   if ((inputValues[0]<-1.826406837)) rval+=-0.4644124098;   // importance = 0.149
   if ((-0.7728639841<inputValues[3])) rval+=-0.3782329416;   // importance = 0.148
   if ((-1.017732859<inputValues[2])&&(inputValues[3]<1.611072063)) rval+=-0.34195424;   // importance = 0.140
   if ((0.2626647353<inputValues[3])) rval+=-0.3026913852;   // importance = 0.136
   if ((inputValues[3]<-0.4998095632)) rval+=-0.3250985794;   // importance = 0.135
   if ((-0.6091313362<inputValues[1])&&(inputValues[3]<1.298193455)) rval+=-0.3005119035;   // importance = 0.134
   if ((-0.6504082084<inputValues[0])&&(inputValues[3]<0.01861145347)) rval+=-0.4159554736;   // importance = 0.126
   if ((inputValues[2]<0.0630280152)&&(inputValues[3]<-0.2550996244)) rval+=-0.2804558347;   // importance = 0.120
   if ((-0.1289403141<inputValues[0])&&(inputValues[3]<1.967075348)) rval+=-0.2607420865;   // importance = 0.117
   if ((inputValues[0]<2.933335543)&&(inputValues[2]<1.129434466)&&(inputValues[3]<0.6765475869)) rval+=-0.270366091;   // importance = 0.116
   if ((2.179115534<inputValues[0])&&(inputValues[3]<2.591761112)) rval+=-0.4790269968;   // importance = 0.115
   if ((inputValues[0]<-0.6504082084)&&(inputValues[3]<-0.4998095632)) rval+=-0.2871811791;   // importance = 0.114
   if ((inputValues[0]<1.346754789)) rval+=-0.2911615101;   // importance = 0.109
   if ((2.933335543<inputValues[0])) rval+=-0.5685123725;   // importance = 0.108
   if ((1.845093489<inputValues[0])&&(inputValues[3]<2.435966492)) rval+=-0.3484196106;   // importance = 0.097
   if ((inputValues[0]<2.933335543)) rval+=-0.4839923346;   // importance = 0.092
   if ((-0.7739752531<inputValues[0])&&(1.815957785<inputValues[3])) rval+=-0.3365545523;   // importance = 0.088
   if ((1.815957785<inputValues[3])) rval+=-0.3365545523;   // importance = 0.088
   if ((-0.6249440312<inputValues[3])) rval+=-0.2075181205;   // importance = 0.084
   if ((-0.6504082084<inputValues[0])&&(-1.834776163<inputValues[1])&&(inputValues[3]<2.758821964)) rval+=-0.1796297538;   // importance = 0.080
   if ((-0.6504082084<inputValues[0])&&(-1.834776163<inputValues[1])&&(inputValues[3]<3.593655825)) rval+=-0.1755663726;   // importance = 0.077
   if ((inputValues[1]<-0.05838980153)&&(inputValues[3]<-0.2550996244)) rval+=-0.2053487972;   // importance = 0.072
   if ((-0.7739752531<inputValues[0])&&(0.8023851514<inputValues[2])&&(1.815957785<inputValues[3])) rval+=-0.2763711287;   // importance = 0.070
   if ((-0.4694648087<inputValues[2])&&(inputValues[3]<0.7908927798)) rval+=-0.1541082765;   // importance = 0.067
   if ((-0.6504082084<inputValues[0])&&(-1.834776163<inputValues[1])&&(inputValues[3]<1.420717359)) rval+=-0.1463349544;   // importance = 0.066
   if ((inputValues[1]<-0.1328951567)&&(-1.640885353<inputValues[3])) rval+=0.143473764;   // importance = 0.064
   if ((-0.05838980153<inputValues[1])&&(inputValues[3]<-0.2550996244)) rval+=-0.1680726501;   // importance = 0.059
   if ((0.5411278009<inputValues[0])&&(-1.017732859<inputValues[2])&&(1.611072063<inputValues[3])) rval+=-0.186764981;   // importance = 0.055
   if ((-1.017732859<inputValues[2])&&(1.611072063<inputValues[3])) rval+=-0.1864327321;   // importance = 0.055
   if ((inputValues[0]<-2.20457983)&&(-2.033569098<inputValues[3])) rval+=0.2338855271;   // importance = 0.051
   if ((-0.6091313362<inputValues[1])&&(1.298193455<inputValues[3])) rval+=-0.1600793433;   // importance = 0.049
   if ((-0.6504082084<inputValues[0])&&(inputValues[0]<4.640089035)&&(-1.834776163<inputValues[1])&&(inputValues[3]<2.758821964)) rval+=-0.1086492557;   // importance = 0.048
   if ((0.0630280152<inputValues[2])&&(inputValues[3]<1.964928746)) rval+=-0.1080910957;   // importance = 0.048
   if ((-0.6504082084<inputValues[0])&&(inputValues[0]<2.681959629)&&(-1.834776163<inputValues[1])&&(inputValues[2]<1.354644775)&&(inputValues[3]<1.420717359)) rval+=0.1046400198;   // importance = 0.047
   if ((-0.7739752531<inputValues[0])&&(inputValues[2]<0.8023851514)&&(0.4605380297<inputValues[3])) rval+=0.1325412442;   // importance = 0.046
   if ((-0.6504082084<inputValues[0])&&(inputValues[1]<-1.834776163)&&(inputValues[3]<0.01861145347)) rval+=-0.4328861505;   // importance = 0.042
   if ((-1.640885353<inputValues[3])) rval+=0.1294538514;   // importance = 0.032
   if ((-1.67862308<inputValues[0])&&(inputValues[0]<2.933335543)&&(0.6765475869<inputValues[3])) rval+=-0.07730026572;   // importance = 0.032
   if ((inputValues[0]<-2.20457983)&&(inputValues[1]<-0.4922137856)&&(-2.033569098<inputValues[3])) rval+=0.2549478187;   // importance = 0.032
   if ((inputValues[0]<2.933335543)&&(0.6765475869<inputValues[3])) rval+=-0.0769866111;   // importance = 0.032
   if ((inputValues[1]<0.6521647573)&&(-0.4694648087<inputValues[2])&&(inputValues[3]<0.7908927798)) rval+=-0.06604983877;   // importance = 0.027
   if ((-0.6504082084<inputValues[0])&&(inputValues[0]<2.681959629)&&(-1.834776163<inputValues[1])&&(inputValues[3]<1.420717359)) rval+=-0.05786752667;   // importance = 0.026
   if ((inputValues[1]<0.6521647573)&&(-0.4694648087<inputValues[2])&&(inputValues[2]<1.178842902)&&(inputValues[3]<0.7908927798)) rval+=0.06056996269;   // importance = 0.024
   if ((-0.6504082084<inputValues[0])&&(inputValues[0]<2.681959629)&&(-1.834776163<inputValues[1])&&(1.354644775<inputValues[2])&&(inputValues[3]<1.420717359)) rval+=-0.1937572177;   // importance = 0.023
   if ((0.6521647573<inputValues[1])&&(-0.4694648087<inputValues[2])&&(inputValues[3]<0.7908927798)) rval+=-0.08611849057;   // importance = 0.022
   if ((inputValues[0]<2.933335543)&&(-2.572238684<inputValues[3])) rval+=0.09339945215;   // importance = 0.020
   if ((-1.826406837<inputValues[0])&&(inputValues[0]<2.393837452)&&(inputValues[3]<0.6982845068)) rval+=-0.04382476905;   // importance = 0.020
   if ((-0.6504082084<inputValues[0])&&(inputValues[0]<2.681959629)&&(-1.834776163<inputValues[1])&&(0.9805320501<inputValues[2])&&(inputValues[2]<1.354644775)&&(inputValues[3]<1.420717359)) rval+=0.1153098673;   // importance = 0.019
   if ((inputValues[0]<-2.20457983)&&(inputValues[1]<-0.4922137856)&&(-3.226956606<inputValues[3])) rval+=-0.1103316713;   // importance = 0.018
   if ((-1.67862308<inputValues[0])&&(inputValues[0]<2.933335543)&&(0.2120489627<inputValues[1])&&(0.6765475869<inputValues[3])) rval+=-0.05686472055;   // importance = 0.017
   if ((-1.826406837<inputValues[0])&&(inputValues[3]<0.6982845068)) rval+=-0.03419074302;   // importance = 0.015
   if ((-0.1328951567<inputValues[1])&&(-1.640885353<inputValues[3])) rval+=-0.03299060767;   // importance = 0.015
   if ((-2.153701067<inputValues[3])) rval+=-0.07780494575;   // importance = 0.013
   if ((0.0630280152<inputValues[2])&&(inputValues[3]<-0.2550996244)) rval+=-0.06914574296;   // importance = 0.011
   if ((inputValues[0]<2.933335543)&&(1.129434466<inputValues[2])&&(inputValues[3]<0.6765475869)) rval+=-0.1148442283;   // importance = 0.010
   if ((-2.20457983<inputValues[0])&&(-1.138035059<inputValues[3])) rval+=-0.02243464557;   // importance = 0.008
   if ((-3.914971352<inputValues[0])&&(inputValues[0]<-0.7739752531)&&(-1.337352514<inputValues[3])) rval+=-0.01827393653;   // importance = 0.007
   if ((inputValues[0]<-0.7739752531)&&(-1.337352514<inputValues[3])) rval+=-0.01827393653;   // importance = 0.007
   if ((inputValues[2]<-1.174188495)&&(-0.2550996244<inputValues[3])) rval+=-0.09216314582;   // importance = 0.006
   if ((-1.67862308<inputValues[0])&&(inputValues[0]<2.933335543)&&(inputValues[1]<0.2120489627)&&(0.6765475869<inputValues[3])) rval+=0.01541374029;   // importance = 0.005
   if ((-0.6504082084<inputValues[0])&&(-1.834776163<inputValues[1])&&(inputValues[3]<0.01861145347)) rval+=0.01488968583;   // importance = 0.004
   if ((2.179115534<inputValues[0])&&(inputValues[3]<1.150868058)) rval+=-0.05549261502;   // importance = 0.004
   if ((inputValues[0]<-2.20457983)&&(-0.4922137856<inputValues[1])&&(-2.033569098<inputValues[3])) rval+=-0.02316892032;   // importance = 0.004
   if ((-0.6504082084<inputValues[0])&&(inputValues[3]<-0.4998095632)) rval+=-0.02165282547;   // importance = 0.004
   if ((inputValues[0]<-2.20457983)&&(-0.4922137856<inputValues[1])&&(inputValues[1]<0.4502070844)&&(-2.033569098<inputValues[3])) rval+=-0.03028643607;   // importance = 0.004
   if ((-0.7739752531<inputValues[0])&&(inputValues[2]<0.8023851514)&&(1.815957785<inputValues[3])) rval+=-0.04421897985;   // importance = 0.003
   //
   // here follows all linear terms
   // at the end of each line, the relative importance of the term is given
   //
   rval+=-0.6111737304*std::min( double(3.426018476), std::max( double(inputValues[0]), double(-3.420648575)));   // importance = 1.000
   rval+=-0.1354361994*std::min( double(2.153379917), std::max( double(inputValues[1]), double(-2.174304962)));   // importance = 0.141
   rval+=-0.162824348*std::min( double(2.059992075), std::max( double(inputValues[2]), double(-2.086013556)));   // importance = 0.164
   rval+=0.5743920633*std::min( double(2.61591959), std::max( double(inputValues[3]), double(-2.359440565)));   // importance = 0.687
   return rval;
}
   inline double ReadRuleFit::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
